<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body>

    <div class="container">
      <!-- header area -->
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Cities</h4>
        </div>
      </div>  
      <!-- header area ends -->
      
      <!-- content area -->
      <div>
        <form method="post" action="<?php echo $data['router']->pathFor('save'); ?>">
          <div class="form-group">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city">
          </div>
          <div class="form-group">
            <button type="submit" name="submit" class="btn btn-primary">Save</button>
          </div>
        </form>  
        
        <table class="table table-border">
          <thead>
            <tr>
              <th>#</th>
              <th>City</th>
              <th></th>
            </tr>
          </thead>
          <?php foreach ($data['cities'] as $city): ?>
          <tr>
            <td><?php echo htmlspecialchars($city['id'], ENT_COMPAT, 'UTF-8'); ?></td>
            <td><?php echo htmlspecialchars($city['name'], ENT_COMPAT, 'UTF-8'); ?></td>
            <td><a role="button" class="btn btn-primary btn-sm" href="<?php echo $data['router']->pathFor('delete', array('id' => htmlspecialchars($city['id'], ENT_COMPAT, 'UTF-8'))); ?>">Delete</a></td>
          </tr>
          <?php endforeach; ?>
        </table>
      </div>        
      <!-- content area ends-->
      
      <!-- footer -->
      <div>
      </div> 
      <!-- footer ends -->
    </div> 

     
  </body>
</html>